---
- hosts: tencent2
  vars:
    tmp_dir: /tmp
    data_dir: /data/tools/code-generator
    gz_name: code-generator.tar.gz
  tasks:
    - name: package
      connection: local
      shell: cd .. && npm rebuild node-sass && npm run generate
    - name: tar
      connection: local
      shell: tar -czf ../../{{gz_name}} ../dist --exclude=.idea --exclude=.git --exclude=ansible --exclude README.md --exclude LICENSE
    - name: mkdir tmp dir
      shell: mkdir -p {{tmp_dir}}/code-generator
    - name: deploy
      copy: src=../../{{gz_name}} dest={{tmp_dir}}
    - name: xtar
      shell: tar -xzf  {{tmp_dir}}/{{gz_name}} -C {{data_dir}}  --strip-components 1
